import { StyleSheet } from "react-native";

export default StyleSheet.create({
    solutionCard: {
        //display: "flex",
        //position: "absolute",
        height: "10%",
        width: "40%",
        //marginTop: "60%",
        backgroundColor: "grey",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "black",
        borderRadius: 4,
        overflow: "visible",
        //backgroundColor: "pink",
    },
    cardText: {
        fontFamily: "FontReg",
        fontStyle: "normal",
        fontWeight: "normal",
        fontSize: 30,
        //lineHeight: 40,
        textAlign: "center",
    },
    colorButton: {
        display: "flex",
        height: "100%",
        width: "40%",
        backgroundColor: "grey",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "black",
        borderRadius: 4,
        shadowColor: "black",
        shadowOffset: {
            width: 0,
            height: 6,
        },
        shadowOpacity: 0.75,
        shadowRadius: 4.65,
        elevation: 6,
    }, 
});