import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    //justifyContent: "center",
    //alignItems: "center",
    flex: 1,
    //backgroundColor: "grey",
  },
  markView: {
    height: "30%",
    //justifyContent: "flex-end",
    //alignItems: "center",
    //marginTop: "70%",
    marginBottom: "-3%",
    zIndex: 2,
    // backgroundColor: "grey",
  },
  solutionCard: {
    height: "45%",
    width: "55%",
    //backgroundColor: "grey",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "black",
    borderRadius: 4,
    overflow: "visible",
    //backgroundColor: "pink",
  },
  cardText: {
    fontFamily: "FontReg",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 30,
    textAlign: "center",
  },
  buttonView: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    height: "45%",
    width: "100%",
    //padding: "5%",
    //marginTop: "50%",
    backgroundColor: "blue",
  },
  colorButton: {
    display: "flex",
    height: "100%",
    width: "40%",
    //backgroundColor: "grey",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "black",
    borderRadius: 4,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.75,
    shadowRadius: 4.65,
    elevation: 6,
  },
});
