import { StyleSheet } from "react-native";
import { color } from "react-native-reanimated";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#39565F",
  },
  backImage: {
    width: "100%",
    height: "100%",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
  },
  fruitZone: {
    position: "absolute",
    marginLeft: 10,
    marginRight: 10,
    top: 200,
    width: 400,
    height: 360,
  },
  fruit: {
    position: "absolute",
    width: 31,
    height: 36,
  },
  sprit: {
    position: "absolute",
    width: 116,
    height: 213,
    marginLeft: -20,
  },
  spritBox: {
    position: "absolute",
    marginLeft: 10,
    marginRight: 10,
    top: 575,
    width: 300,
    height: 200,
  },
  spritBox2: {
    position: "absolute",
    marginLeft: 10,
    marginRight: 10,
    top: 300,
    width: 300,
    height: 200,
  },
  spritBox3: {
    position: "absolute",
    marginLeft: 10,
    marginRight: 10,
    top: 200,
    width: 300,
    height: 200,
    alignItems: "flex-end",
  },
  textBox: {
    position: "absolute",
    top: 775,
    height: 82,
    width: 300,
    borderRadius: 5,
    padding: 10,
    backgroundColor: "#3B96B3",
    alignItems: "center",
    justifyContent: "center",
  },
  textBox2: {
    height: 82,
    width: 300,
    borderRadius: 5,
    padding: 10,
    backgroundColor: "#3B96B3",
    alignItems: "center",
    justifyContent: "center",
  },
  itemBoxes: {
    position: "absolute",
    width: 400,
    height: 47,
    top: 130,
    left: 40,
  },
  itemBox: {
    height: 48,
    width: 47,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DCF4F1",
    margin: 1,
  },
  boxImg: {
    height: 40,
    width: 40,
    resizeMode: "contain",
  },
  countDis: {
    position: "absolute",
    height: 30,
    width: 100,
    top: 100,
    alignItems: "center",
    justifyContent: "center",
  },
  recpImgBox: {
    height: 150,
    width: 200,
    left: 90,
    top: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  groupImg: {
    resizeMode: "contain",
  },
  nextButton: {
    width: 163,
    height: 51,
    borderRadius: 41,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 60,
  },
  buttonView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: 350,
    height: 51,
    marginTop: 60,
  },
  navButton: {
    width: 163,
    height: 51,
    borderRadius: 41,
    margin: 10,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  fin: {
    width: 350,
    height: 300,
    marginTop: 430,
    alignItems: "center",
  },
  starting: {
    width: 350,
    height: 300,
    marginTop: 350,
    alignItems: "center",
  },
  exitPosition: {
    alignSelf: "flex-start",
    marginLeft: 50,
    marginTop: 40,
  },
});
