name: Build CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Packages install
        run: npm ci

      - name: Run tests
        run: npm test

  publish:
    name: Setup expo tools and publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Packages install
        run: npm install --production
        env:
          NODE_ENV: production

      - name: Setup expo CLI with token access
        uses: expo/expo-github-action@v5
        with:
          expo-patch-watchers: false
          expo-packager: npm
          expo-token: ${{ secrets.EXPO_TOKEN }}
        env:
          NODE_ENV: production

      - name: Publish update
        run: expo publish --target managed --release-channel dev
